"""Calibrated priors store — the data-fusion layer.

The per-circuit constants in ``models.circuits`` and ``models.params`` are
*priors grounded in published work* (Heilmeier 2014-2019). This module replaces
them, where we have evidence, with values fit from recent real races and
persisted to ``calibrated/priors.json``:

  * per-circuit P(>=1 SC) and P(>=1 VSC)           — from FastF1 race-control
  * per-circuit pit-lane loss mean + sd            — from PitOut-PitIn telemetry
  * SC / VSC cheap-stop discount fractions         — green vs neutralised stops
  * per-circuit race-pace gap (base - pole)        — from qualifying
  * a shared tyre thermal coupling (s/lap per °C)  — from pooled, weather-joined laps
  * per-constructor mechanical-DNF probability     — from Jolpica results

``apply_to_model`` folds these into a ``RaceModel`` on the high-fidelity Python
paths (ghost / backtest / live). It is deliberately *not* wired into
``RaceModel.for_circuit`` so the default model — and the Rust parity test that
uses it — stays untouched; calibration is opt-in per call site.

The JSON is regenerated by ``scripts/build_priors.py`` (a parallel sweep over the
calendar). If it is absent every accessor degrades gracefully to the priors.
"""

from __future__ import annotations

import json
from dataclasses import replace
from functools import lru_cache
from pathlib import Path

PRIORS_PATH = Path(__file__).resolve().parent / "calibrated" / "priors.json"


@lru_cache(maxsize=1)
def load_priors() -> dict:
    """Load the calibrated priors JSON (cached). Returns ``{}`` if not built."""
    try:
        return json.loads(PRIORS_PATH.read_text())
    except Exception:
        return {}


def save_priors(data: dict) -> None:
    PRIORS_PATH.parent.mkdir(parents=True, exist_ok=True)
    PRIORS_PATH.write_text(json.dumps(data, indent=2, sort_keys=True))
    load_priors.cache_clear()


def circuit_prior(circuit_id: str) -> dict:
    return load_priors().get("circuits", {}).get(circuit_id, {})


def tyre_temp_prior() -> tuple[float, float]:
    """(temp_coeff, temp_ref). Falls back to an inert (0, 30)."""
    t = load_priors().get("tyre_temp", {})
    return float(t.get("temp_coeff", 0.0)), float(t.get("temp_ref", 30.0))


def wet_prior() -> dict:
    """Calibrated intermediate / full-wet pace deficits, or ``{}`` if unbuilt."""
    return load_priors().get("wet", {})


def reliability_for(constructor: str | None) -> float | None:
    """Per-constructor mechanical-DNF probability, or the field overall, or None."""
    rel = load_priors().get("reliability", {})
    if not rel:
        return None
    if constructor and constructor in rel:
        return float(rel[constructor]["p_dnf"])
    ov = rel.get("_overall")
    return float(ov) if ov is not None else None


# Map FastF1/Jolpica team names to the Jolpica constructorId used in the priors.
_TEAM_ALIASES = {
    "red bull racing": "red_bull", "red bull": "red_bull",
    "mercedes": "mercedes", "ferrari": "ferrari", "mclaren": "mclaren",
    "aston martin": "aston_martin", "alpine": "alpine", "williams": "williams",
    "rb": "rb", "racing bulls": "rb", "alphatauri": "alphatauri",
    "kick sauber": "sauber", "sauber": "sauber", "alfa romeo": "alfa",
    "haas f1 team": "haas", "haas": "haas",
}


def constructor_id(team: str | None) -> str | None:
    if not team:
        return None
    return _TEAM_ALIASES.get(str(team).strip().lower())


def apply_to_model(model, *, circuit_id: str, constructor: str | None = None,
                   track_temp: float | None = None, with_dirty_air: bool = True):
    """Return a copy of ``model`` with calibrated priors folded in.

    Only touches fields we have evidence for; everything else keeps its prior.
    ``constructor`` (a team name) selects per-team reliability; ``track_temp``
    overrides the temperature the tyre model is evaluated at (for a live weather
    feed). Pit-loss variance and dirty-air pace loss are turned on here because
    these paths use the pure-Python reference simulator."""
    cp = circuit_prior(circuit_id)
    pit = model.pit
    pace = model.pace
    tyres = model.tyres
    sc = model.safety_car
    ov = model.overtake
    cfg = model.config
    wet = model.wet

    # --- wet-tyre pace deficits (calibrated from real wet races) -------------
    wp = wet_prior()
    if wp.get("inter_floor") is not None:
        wet = replace(wet, inter_floor=float(wp["inter_floor"]))
    if wp.get("wet_floor") is not None:
        wet = replace(wet, wet_floor=float(wp["wet_floor"]))

    # --- pit loss (mean + real crew variance) + cheap-stop discounts ---------
    if cp.get("pit_loss_mean"):
        pl = float(cp["pit_loss_mean"])
        pit = replace(pit, pit_loss_s=pl)
        cfg = replace(cfg, pit_loss_s=pl)
    if cp.get("pit_loss_sd") is not None:
        pit = replace(pit, pit_loss_sd=float(cp["pit_loss_sd"]))
    if cp.get("sc_frac") is not None:
        pit = replace(pit, sc_saving_frac=float(cp["sc_frac"]))
    if cp.get("vsc_frac") is not None:
        pit = replace(pit, vsc_saving_frac=float(cp["vsc_frac"]))

    # --- safety-car probability ---------------------------------------------
    if cp.get("p_sc") is not None:
        sc = replace(sc, p_at_least_one_override=float(cp["p_sc"]))

    # --- per-constructor reliability ----------------------------------------
    p_dnf = reliability_for(constructor_id(constructor))
    if p_dnf is not None:
        sc = replace(sc, team_failure_prob=float(p_dnf))

    # --- race-pace gap from qualifying --------------------------------------
    if cp.get("race_pace_gap"):
        pace = replace(pace, race_pace_gap=float(cp["race_pace_gap"]))

    # --- tyre thermal coupling ----------------------------------------------
    # Respect a coupling already fitted on this model; only fill from the pooled
    # prior when the model carries none. A live track_temp always overrides.
    if tyres.temp_coeff:
        if track_temp is not None:
            tyres = replace(tyres, track_temp=track_temp)
    else:
        tcoeff, tref = tyre_temp_prior()
        if tcoeff:
            tt = track_temp if track_temp is not None else tref
            tyres = replace(tyres, temp_coeff=tcoeff, temp_ref=tref, track_temp=tt)

    # --- dirty-air pace loss -------------------------------------------------
    # Prefer the value fitted from real wake telemetry (calibrate_dirty_air);
    # fall back to a difficulty-scaled prior (0.15..0.45 s/lap) only where no fit
    # is available. This is the pace tax a car pays stuck in traffic, so escaping
    # it via a pit has real value — the biggest lever on undercut/overcut worth.
    if with_dirty_air:
        if cp.get("dirty_air_loss_s") is not None:
            loss = float(cp["dirty_air_loss_s"])
        else:
            loss = round(0.15 + 0.30 * float(cfg.overtaking_difficulty), 3)
        ov = replace(ov, dirty_air_loss_s=loss)

    return replace(model, pit=pit, pace=pace, tyres=tyres,
                   safety_car=sc, overtake=ov, config=cfg, wet=wet)
